import { StyleSheet } from "react-native";

export default StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: "#ffffff",
  },
  content: {
    paddingVertical: 16,
    paddingHorizontal: 16,
    alignItems: "center",
  },
  userCard: {
    backgroundColor: "#F3F4F6",
    borderRadius: 17,
    paddingVertical: 10,
    paddingHorizontal: 10,
    width: "100%",
    alignItems: "center",
  },
  userName: {
    fontSize: 30,
    fontWeight: "600",
    color: "#1F2937",
    margin: -3,
  },
  userEmail: {
    fontSize: 18,
    color: "#6B7280",
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "#E5E7EB",
    marginVertical: 14,
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    justifyContent: "center",
  },
  statCard: {
    backgroundColor: "#ffffff",
    borderRadius: 25,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",

    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  statValue: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#111827",
    margin: -3,
  },
  statLabel: {
    fontSize: 12,
    color: "#6B7280",
    fontWeight: "600",
    textAlign: "center",
  },
  menuContainer: {
    width: "100%",
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 99999,
    paddingVertical: 7,
    paddingHorizontal: 9,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  menuIconContainer: {
    backgroundColor: "#F5F3FF",
    padding: 10,
    borderRadius: 99999,
    marginRight: 15,
  },
  menuItemText: {
    flex: 1,
    fontSize: 18,
    fontWeight: "600",
    color: "#374151",
  },
  logoutContainer: {
    position: "absolute",
    bottom: 16,
    right: 16,
  },
  logoutButton: {
    width: 60,
    height: 60,
    backgroundColor: "#EF4444",
    borderRadius: 35,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#EF4444",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 30,
    padding: 25,
    width: "100%",
    maxWidth: 400,
    alignItems: "flex-start",
    position: "relative",
  },
  modalCloseButton: {
    position: "absolute",
    top: 15,
    right: 15,
    backgroundColor: "#FF3B30",
    borderRadius: 10,
    padding: 4,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#1F2937",
    marginBottom: 15,
    marginTop: 10,
  },
  modalInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    color: "#1F2937",
    marginBottom: 25,
    backgroundColor: "#FAFAFA",
  },
  modalSaveButton: {
    backgroundColor: "#AD46FF",
    borderRadius: 15,
    paddingVertical: 18,
    width: "100%",
    alignItems: "center",
    shadowColor: "#AD46FF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  modalSaveButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
});
